aux = input("Digite algo: ")

print("O resultado é maiusculo?",aux.isupper())
print("O resultado é alpha numerico?",aux.isalnum())
print("O resultado é alfabetico?",aux.isalpha())
print("O resultado é um codigo da tabela ascii?",aux.isascii())
print("O resultado é decimal?",aux.isdecimal())
print("O resultado é 'digit'?",aux.isdigit())
print("O resultado é 'identifier'?",aux.isidentifier())
print("O resultado é minusculo?",aux.islower())
print("O resultado é numero?",aux.isnumeric())
print("O resultado é 'printavel'?",aux.isprintable())
print("O resultado é 'space'?",aux.isspace())
print("O resultado é um titulo?",aux.istitle())